float32 right_stick_x_axis
float32 right_stick_y_axis
float32 left_stick_x_axis
float32 left_stick_y_axis
float32 l_trigger
float32 r_trigger

bool dpad_up
bool dpad_up_left
bool dpad_up_right
bool dpad_down
bool dpad_down_left
bool dpad_down_right
bool dpad_left
bool dpad_right

bool a_button
bool b_button
bool x_button
bool y_button

bool l1_button
bool l2_button
bool l3_button
bool r1_button
bool r2_button
bool r3_button

bool select_button
bool start_button
bool center_button